i18n:
  structure: single_file
  locales: [en, ru]
  default_locale: en
backend:
  name: git-gateway
  branch: main
media_folder: img
publish_mode: editorial_workflow
collections:
  - label: "Model"
    name: "model"
    i18n: true
    folder: "models"
    create: true
    publish: false
    fields:
      - {label: "Title", name: "title", widget: "string",i18n: true}
      - {label: "Brand", name: "brand", widget: "relation", collection: "brand", value_field: "title", search_fields: ["brand"],i18n: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image",i18n: duplicate}
      - {label: "Publish Date", name: "date", widget: "datetime",i18n: duplicate}
  - label: "Brand"
    name: "brand"
    i18n: true
    folder: "brands"
    create: true
    publish: true
    fields:
      - {label: "Title", name: "title", widget: "string",i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime",i18n: duplicate}
      
