backend:
  name: git-gateway
local_backend:
  #  for local development start npx @staticcms/proxy-server first
  url: http://127.0.0.1:8081/api/v1
i18n:
  structure: single_file
  locales: [en, de, fr, ru]
  defaultLocale: en
media_folder: img
logo_url: roon.jpg
collections:
  - label: Models
    name: model
    folder: models
    format: json
    create: true
    publish: true
    delete: true
    i18n: true
    #  slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    slug: "{{brand}}-{{title}}"
    summary: "{{brand}} {{title}} {{yta}}"
    sortable_fields:
      fields: ["brand", "yta"]
      default:
        field: brand
        direction: Ascending
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Brand
        name: brand
        required: true
        widget: relation
        collection: brands
        value_field: "{{slug}}"
        display_fields:
          - title
        search_fields:
          - title
      - label: Input
        name: Input
        required: false
        widget: select
        options: ["Ethernet", "Wi-Fi"]
        multiple: true
      - label: Type
        name: type
        widget: relation
        required: false
        collection: types
        value_field: "{{slug}}"
        display_fields:
          - title
        search_fields:
          - title
      - label: Image (only B&W thumbs!)
        name: image
        widget: image
        required: false
      - label: Year to announce
        name: yta
        required: false
        widget: number
        value_type: int
        min: 2010
        max: 2030
      - label: Manufaturer's recommended price (USD)
        name: mrp
        widget: number
        required: false
        value_type: int
        min: 10
        max: 50000
      - label: Remarks (for selected language)
        name: remark
        i18n: true
        widget: text
        required: false
      - label: Description (for selected language)
        name: desc
        i18n: true
        widget: markdown
        required: false
      - label: Datasource and other proof links
        name: dsl
        widget: list
        required: false
        fields:
          - label: Link description
            name: linkdesc
            widget: string
            required: false
            i18n: true
          - label: URL
            name: linkurl
            required: false
            widget: string
            i18n: true

      - label: Manufaturer's  website links (for selected language)
        name: mwl
        widget: object
        required: false
        i18n: true
        fields:
          - label: Product Page URL
            name: ppl
            widget: string
            i18n: true
            required: false
          - label: User's support page URL
            name: uspl
            widget: string
            i18n: true
            required: false
      - label: Related links (reviews etc.) (for selected language)
        name: rl
        widget: list
        i18n: true
        required: false
        fields:
          - label: Link description
            name: linkdesc
            widget: string
            required: false
            i18n: true
          - label: URL
            name: linkurl
            required: false
            widget: string
            i18n: true
      - label: Yandex Model
        name: yamodel
        widget: string
        required: false
  - label: Brands
    name: brands
    folder: brands
    format: json
    create: true
    publish: true
    delete: false
    ##  slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - label: Title
        name: title
        required: true
        widget: string
  - label: Types
    name: types
    i18n: true
    folder: types
    format: json
    create: true
    publish: true
    delete: false
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - label: Title
        name: title
        widget: string
        required: true
        i18n: true
  - label: Colors
    name: colors
    i18n: true
    folder: colors
    format: json
    create: true
    publish: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
        required: false
        i18n: true
  - label: Markets
    name: markets
    i18n: true
    folder: markets
    format: json
    create: true
    publish: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
        required: false
        i18n: true
  - label: Variants
    name: variants
    i18n: true
    folder: variants
    format: json
    create: true
    publish: true
    delete: false
    slug: "{{model}}-{{color}}-{{feature}}"
    identifier_field: model
    summary: "{{model}} {{color}} {{feature}}"
    fields:
      - label: Model
        name: model
        widget: relation
        collection: model
        required: true
        i18n: false
        value_field: "{{slug}}"
        display_fields:
          - brand
          - title
        search_fields:
          - title
      - label: Color
        name: color
        widget: relation
        collection: colors
        required: true
        i18n: false
        value_field: "{{slug}}"
        display_fields:
          - title
        search_fields:
          - title
      - label: Distinctive feature
        name: feature
        widget: string
        i18n: true
        required: false
      - label: Offers
        name: offers
        widget: list
        i18n: false
        required: false
        fields:
          - label: Markets
            name: markets
            widget: relation
            required: false
            collection: markets
            value_field: "{{slug}}"
            display_fields:
              - title
            search_fields:
              - title
            multiple: true
          - label: URL
            name: url
            required: false
            widget: string
