backend:
  name: git-gateway
  branch: main
media_folder: img
collections:
  - label: "Model"
    name: "model"
    folder: "models"
    format: "json"
    create: true
    publish: true
    delete: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Brand
        name: brand
        widget: relation
        collection: brands
        value_field: '{{slug}}'
        display_fields:
          - title
        search_fields:
          - title  
  - label: "Brand"
    name: "brands"
    folder: "brands"
    create: true
    publish: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string  
