backend:
  name: git-gateway
  branch: main
media_folder: img
publish_mode: editorial_workflow
collections:
  - label: "Model"
    name: "model"
    folder: "models"
    format: "json"
    create: true
    publish: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Brand", name: "brand", widget: "relation", collection: "brand", value_field: "title", search_fields: ["brand"]}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - label: "Brand"
    name: "brand"
    folder: "brands"
    create: true
    publish: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}     
