backend:
  name: git-gateway
local_backend:
  #  for local development start npx @staticcms/proxy-server first
  url: http://127.0.0.1:8081/api/v1
i18n:
  structure: single_file
  locales: [en, de, fr, ru]
  defaultLocale: en
media_folder: img
logo_url: roon.jpg
collections:
  - label: Models
    name: model
    folder: data/models
    format: json
    create: true
    publish: true
    delete: true
    i18n: true
    #  slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    slug: "{{brand}}-{{title}}"
    summary: "{{brand}} {{title}} {{yta}}"
    sortable_fields:
      fields: ["brand", "yta"]
      default:
        field: brand
        direction: Ascending
    fields:
      - label: Brand
        name: brand
        required: true
        widget: relation
        collection: brands
        value_field: "{{slug}}"
        display_fields:
          - title
        search_fields:
          - title
      - label: Model name
        name: title
        widget: string
        required: true
      - label: essential links (for selected language)
        name: essential_links
        widget: object
        required: false
        i18n: true
        fields:
          - label: Product Page URL
            name: manufacturers_site_product_page_url
            widget: string
            i18n: true
            required: false
          - label: User's manual  URL
            name: manual_url
            widget: string
            i18n: true
            required: false
      - label: Input
        name: Input
        required: false
        widget: select
        options: ["Ethernet", "Wi-Fi"]
        multiple: true
        i18n: false
      - label: Type
        name: type
        widget: relation
        required: false
        collection: types
        value_field: "{{slug}}"
        display_fields:
          - title
        search_fields:
          - title
      - label: Image (only B&W thumbs!)
        name: image
        widget: image
        required: false
        media_library:
          max_file_size: 51200
          folder_support: true
      - label: Year to announce
        name: yta
        required: false
        widget: number
        value_type: int
        min: 2010
        max: 2030
      - label: Manufaturer's recommended price (USD - or converted to USD)
        name: mrp
        widget: number
        required: false
        value_type: int
        min: 10
        max: 50000
      - label: Remarks (for selected language)
        name: remark
        i18n: true
        widget: text
        required: false
      - label: Description (for selected language)
        name: desc
        i18n: true
        widget: markdown
        required: false

      - label: Related links (reviews etc.) (for selected language)
        name: related_links
        widget: list
        i18n: true
        required: false
        fields:
          - label: Link description
            name: related_link_description
            widget: string
            required: false
            i18n: true
          - label: URL
            name: related_link_url
            required: false
            widget: string
            i18n: true
      - label: Variants and offers
        name: variants
        widget: list
        required: false
        i18n: false
        fields:
          - label: Image
            name: variant_image
            widget: image
            required: false
            media_library:
              max_file_size: 30000
          - label: Color
            name: color
            widget: relation
            collection: colors
            required: false
            i18n: false
            value_field: "{{slug}}"
            display_fields:
              - title
            search_fields:
              - title
          - label: Options (internal featers, bundle with.., etc) and offers
            name: options
            widget: list
            i18n: false
            required: false
            fields:
              - label: distinctive feature presented
                name: fpresented
                widget: boolean
                default: false
                required: true
              - label: Distinctive feature
                name: feature
                widget: string
                i18n: false
                required: false
              - label: Offers
                name: offers
                widget: list
                i18n: false
                required: false
                fields:
                  - label: Markets
                    name: markets
                    widget: relation
                    required: false
                    collection: markets
                    value_field: "{{slug}}"
                    display_fields:
                      - title
                    search_fields:
                      - title
                    multiple: true
                  - label: URL
                    name: url
                    required: false
                    widget: string
      - label: Datasource and other proof links (for editor's internal use)
        name: datasource_link
        widget: list
        required: false
        fields:
          - label: Link description
            name: datasource_link_description
            widget: string
            required: false
            i18n: true
          - label: URL
            name: datasource_link_url
            required: false
            widget: string
            i18n: false
      - label: Editor's comments
        name: editors_comments
        i18n: false
        widget: text
        required: false

  - label: Brands
    name: brands
    folder: data/brands
    format: json
    create: true
    publish: true
    delete: false
    ##  slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - label: Title
        name: title
        required: true
        widget: string
  - label: Types
    name: types
    i18n: true
    folder: data/types
    format: json
    create: true
    publish: true
    delete: false
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - label: Title
        name: title
        widget: string
        required: true
        i18n: true
      - label: Custom sortcode
        name: sortcode
        widget: "number"
        value_type: "int"
  - label: Colors
    name: colors
    i18n: true
    folder: data/colors
    format: json
    create: true
    publish: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
        required: false
        i18n: true
  - label: Markets
    name: markets
    i18n: true
    folder: data/markets
    format: json
    create: true
    publish: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
        required: false
        i18n: true
