backend:
  name: git-gateway
  branch: main
media_folder: img
publish_mode: editorial_workflow
collections:
  - label: "Model"
    name: "model"
    folder: "models"
    create: true
    publish: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
